// This file is auto-generated. Do not edit manually.
import { Language } from '../i18n/translations';

// Static mapping of all onboarding images
const ONBOARDING_IMAGES: Record<string, any> = {
  '1_ar': require('../assets/images/onboarding/onboarding-01_ar.jpg'),
  '1_cs': require('../assets/images/onboarding/onboarding-01_cs.jpg'),
  '1_da': require('../assets/images/onboarding/onboarding-01_da.jpg'),
  '1_de': require('../assets/images/onboarding/onboarding-01_de.jpg'),
  '1_el': require('../assets/images/onboarding/onboarding-01_el.jpg'),
  '1_en': require('../assets/images/onboarding/onboarding-01_en.jpg'),
  '1_es': require('../assets/images/onboarding/onboarding-01_es.jpg'),
  '1_fi': require('../assets/images/onboarding/onboarding-01_fi.jpg'),
  '1_fil': require('../assets/images/onboarding/onboarding-01_fil.jpg'),
  '1_fr': require('../assets/images/onboarding/onboarding-01_fr.jpg'),
  '1_he': require('../assets/images/onboarding/onboarding-01_he.jpg'),
  '1_hi': require('../assets/images/onboarding/onboarding-01_hi.jpg'),
  '1_hu': require('../assets/images/onboarding/onboarding-01_hu.jpg'),
  '1_id': require('../assets/images/onboarding/onboarding-01_id.jpg'),
  '1_it': require('../assets/images/onboarding/onboarding-01_it.jpg'),
  '1_ja': require('../assets/images/onboarding/onboarding-01_ja.jpg'),
  '1_ko': require('../assets/images/onboarding/onboarding-01_ko.jpg'),
  '1_ms': require('../assets/images/onboarding/onboarding-01_ms.jpg'),
  '1_nl': require('../assets/images/onboarding/onboarding-01_nl.jpg'),
  '1_no': require('../assets/images/onboarding/onboarding-01_no.jpg'),
  '1_pl': require('../assets/images/onboarding/onboarding-01_pl.jpg'),
  '1_pt': require('../assets/images/onboarding/onboarding-01_pt.jpg'),
  '1_ro': require('../assets/images/onboarding/onboarding-01_ro.jpg'),
  '1_ru': require('../assets/images/onboarding/onboarding-01_ru.jpg'),
  '1_sv': require('../assets/images/onboarding/onboarding-01_sv.jpg'),
  '1_th': require('../assets/images/onboarding/onboarding-01_th.jpg'),
  '1_tr': require('../assets/images/onboarding/onboarding-01_tr.jpg'),
  '1_uk': require('../assets/images/onboarding/onboarding-01_uk.jpg'),
  '1_vi': require('../assets/images/onboarding/onboarding-01_vi.jpg'),
  '1_zh': require('../assets/images/onboarding/onboarding-01_zh.jpg'),
  '2_ar': require('../assets/images/onboarding/onboarding-02_ar.jpg'),
  '2_cs': require('../assets/images/onboarding/onboarding-02_cs.jpg'),
  '2_da': require('../assets/images/onboarding/onboarding-02_da.jpg'),
  '2_de': require('../assets/images/onboarding/onboarding-02_de.jpg'),
  '2_el': require('../assets/images/onboarding/onboarding-02_el.jpg'),
  '2_es': require('../assets/images/onboarding/onboarding-02_es.jpg'),
  '2_fi': require('../assets/images/onboarding/onboarding-02_fi.jpg'),
  '2_fil': require('../assets/images/onboarding/onboarding-02_fil.jpg'),
  '2_fr': require('../assets/images/onboarding/onboarding-02_fr.jpg'),
  '2_he': require('../assets/images/onboarding/onboarding-02_he.jpg'),
  '2_hi': require('../assets/images/onboarding/onboarding-02_hi.jpg'),
  '2_hu': require('../assets/images/onboarding/onboarding-02_hu.jpg'),
  '2_id': require('../assets/images/onboarding/onboarding-02_id.jpg'),
  '2_it': require('../assets/images/onboarding/onboarding-02_it.jpg'),
  '2_ja': require('../assets/images/onboarding/onboarding-02_ja.jpg'),
  '2_ko': require('../assets/images/onboarding/onboarding-02_ko.jpg'),
  '2_ms': require('../assets/images/onboarding/onboarding-02_ms.jpg'),
  '2_nl': require('../assets/images/onboarding/onboarding-02_nl.jpg'),
  '2_no': require('../assets/images/onboarding/onboarding-02_no.jpg'),
  '2_pl': require('../assets/images/onboarding/onboarding-02_pl.jpg'),
  '2_pt': require('../assets/images/onboarding/onboarding-02_pt.jpg'),
  '2_ro': require('../assets/images/onboarding/onboarding-02_ro.jpg'),
  '2_ru': require('../assets/images/onboarding/onboarding-02_ru.jpg'),
  '2_sv': require('../assets/images/onboarding/onboarding-02_sv.jpg'),
  '2_th': require('../assets/images/onboarding/onboarding-02_th.jpg'),
  '2_tr': require('../assets/images/onboarding/onboarding-02_tr.jpg'),
  '2_uk': require('../assets/images/onboarding/onboarding-02_uk.jpg'),
  '2_vi': require('../assets/images/onboarding/onboarding-02_vi.jpg'),
  '2_zh': require('../assets/images/onboarding/onboarding-02_zh.jpg'),
  '3_ar': require('../assets/images/onboarding/onboarding-03_ar.jpg'),
  '3_cs': require('../assets/images/onboarding/onboarding-03_cs.jpg'),
  '3_da': require('../assets/images/onboarding/onboarding-03_da.jpg'),
  '3_de': require('../assets/images/onboarding/onboarding-03_de.jpg'),
  '3_el': require('../assets/images/onboarding/onboarding-03_el.jpg'),
  '3_es': require('../assets/images/onboarding/onboarding-03_es.jpg'),
  '3_fi': require('../assets/images/onboarding/onboarding-03_fi.jpg'),
  '3_fil': require('../assets/images/onboarding/onboarding-03_fil.jpg'),
  '3_fr': require('../assets/images/onboarding/onboarding-03_fr.jpg'),
  '3_he': require('../assets/images/onboarding/onboarding-03_he.jpg'),
  '3_hi': require('../assets/images/onboarding/onboarding-03_hi.jpg'),
  '3_hu': require('../assets/images/onboarding/onboarding-03_hu.jpg'),
  '3_id': require('../assets/images/onboarding/onboarding-03_id.jpg'),
  '3_it': require('../assets/images/onboarding/onboarding-03_it.jpg'),
  '3_ja': require('../assets/images/onboarding/onboarding-03_ja.jpg'),
  '3_ko': require('../assets/images/onboarding/onboarding-03_ko.jpg'),
  '3_ms': require('../assets/images/onboarding/onboarding-03_ms.jpg'),
  '3_nl': require('../assets/images/onboarding/onboarding-03_nl.jpg'),
  '3_no': require('../assets/images/onboarding/onboarding-03_no.jpg'),
  '3_pl': require('../assets/images/onboarding/onboarding-03_pl.jpg'),
  '3_pt': require('../assets/images/onboarding/onboarding-03_pt.jpg'),
  '3_ro': require('../assets/images/onboarding/onboarding-03_ro.jpg'),
  '3_ru': require('../assets/images/onboarding/onboarding-03_ru.jpg'),
  '3_sv': require('../assets/images/onboarding/onboarding-03_sv.jpg'),
  '3_th': require('../assets/images/onboarding/onboarding-03_th.jpg'),
  '3_tr': require('../assets/images/onboarding/onboarding-03_tr.jpg'),
  '3_uk': require('../assets/images/onboarding/onboarding-03_uk.jpg'),
  '3_vi': require('../assets/images/onboarding/onboarding-03_vi.jpg'),
  '3_zh': require('../assets/images/onboarding/onboarding-03_zh.jpg'),
  '4_ar': require('../assets/images/onboarding/onboarding-04_ar.jpg'),
  '4_cs': require('../assets/images/onboarding/onboarding-04_cs.jpg'),
  '4_da': require('../assets/images/onboarding/onboarding-04_da.jpg'),
  '4_de': require('../assets/images/onboarding/onboarding-04_de.jpg'),
  '4_el': require('../assets/images/onboarding/onboarding-04_el.jpg'),
  '4_es': require('../assets/images/onboarding/onboarding-04_es.jpg'),
  '4_fi': require('../assets/images/onboarding/onboarding-04_fi.jpg'),
  '4_fr': require('../assets/images/onboarding/onboarding-04_fr.jpg'),
  '4_he': require('../assets/images/onboarding/onboarding-04_he.jpg'),
  '4_hi': require('../assets/images/onboarding/onboarding-04_hi.jpg'),
  '4_hu': require('../assets/images/onboarding/onboarding-04_hu.jpg'),
  '4_id': require('../assets/images/onboarding/onboarding-04_id.jpg'),
  '4_it': require('../assets/images/onboarding/onboarding-04_it.jpg'),
  '4_ja': require('../assets/images/onboarding/onboarding-04_ja.jpg'),
  '4_ko': require('../assets/images/onboarding/onboarding-04_ko.jpg'),
  '4_ms': require('../assets/images/onboarding/onboarding-04_ms.jpg'),
  '4_nl': require('../assets/images/onboarding/onboarding-04_nl.jpg'),
  '4_no': require('../assets/images/onboarding/onboarding-04_no.jpg'),
  '4_pl': require('../assets/images/onboarding/onboarding-04_pl.jpg'),
  '4_pt': require('../assets/images/onboarding/onboarding-04_pt.jpg'),
  '4_ro': require('../assets/images/onboarding/onboarding-04_ro.jpg'),
  '4_ru': require('../assets/images/onboarding/onboarding-04_ru.jpg'),
  '4_sv': require('../assets/images/onboarding/onboarding-04_sv.jpg'),
  '4_th': require('../assets/images/onboarding/onboarding-04_th.jpg'),
  '4_tr': require('../assets/images/onboarding/onboarding-04_tr.jpg'),
  '4_uk': require('../assets/images/onboarding/onboarding-04_uk.jpg'),
  '4_vi': require('../assets/images/onboarding/onboarding-04_vi.jpg'),
  '4_zh': require('../assets/images/onboarding/onboarding-04_zh.jpg'),
};

export function getOnboardingImage(slideNumber: number, language: Language): any {
  // Slide 5 is static (09.png) - same for all languages
  if (slideNumber === 5) {
    return require('../assets/images/onboarding/09.png');
  }

  // Try current language, fallback to English
  const key = `${slideNumber}_${language}`;
  const fallbackKey = `${slideNumber}_en`;

  return ONBOARDING_IMAGES[key] || ONBOARDING_IMAGES[fallbackKey];
}
